//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarielAPI.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLoanRequest
    {
        public int id { get; set; }
        public string deleted { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<int> updatedBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public Nullable<int> loan_WorkflowID { get; set; }
        public Nullable<int> loan_WorkflowItemID { get; set; }
        public Nullable<int> loan_ZoneID { get; set; }
        public Nullable<int> accountID { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> payDay { get; set; }
        public Nullable<System.DateTime> payDate { get; set; }
        public Nullable<decimal> loanAmount { get; set; }
        public Nullable<decimal> interestRate { get; set; }
        public Nullable<decimal> interestAmount { get; set; }
        public string purpose { get; set; }
        public string status { get; set; }
        public string rejectReason { get; set; }
        public string loan_Code { get; set; }
        public Nullable<decimal> loan_PaidAmount { get; set; }
        public Nullable<decimal> loan_Balance { get; set; }
        public Nullable<int> load_DisburstBy { get; set; }
        public Nullable<System.DateTime> load_DisburstOn { get; set; }
    }
}
