//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarielAPI.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPin
    {
        public int id { get; set; }
        public string deleted { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<int> updatedBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public Nullable<int> pins_WorkflowID { get; set; }
        public Nullable<int> pins_WorkflowItemID { get; set; }
        public Nullable<int> pins_ZoneID { get; set; }
        public string name { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> accountID { get; set; }
        public string isUsed { get; set; }
        public string phoneNumber { get; set; }
    }
}
